"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  Activity,
  Boxes,
  CheckCircle2,
  Cloud,
  Cpu,
  Gauge,
  LayoutDashboard,
  Layers3,
  LogOut,
  MemoryStick,
  Play,
  Plus,
  Server,
  Settings,
  ShieldCheck,
  Square,
  TerminalSquare,
  Trash2,
  Users,
  XCircle,
  Zap,
} from "lucide-react";
import { APP_NAME, type ActivityLog, type CloudAccount, type ClusterNode, type CurrentUser, type MpiJob, type VirtualMachine } from "@hpc/shared";
import { API_URL, authClient } from "@/lib/auth-client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Section = "overview" | "vms" | "members" | "nodes" | "accounts" | "activity" | "jobs" | "settings";

async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const headers = new Headers(init?.headers);
  if (init?.body && !headers.has("Content-Type")) headers.set("Content-Type", "application/json");
  const response = await fetch(API_URL + path, { ...init, credentials: "include", headers, cache: "no-store" });
  const body = (await response.json().catch(() => ({}))) as T & { error?: { message?: string } };
  if (!response.ok) { const error = new Error(body.error?.message ?? "The request could not be completed."); Object.assign(error, { status: response.status }); throw error; }
  return body;
}

const nav: Array<{ section: Section; label: string; icon: typeof LayoutDashboard }> = [
  { section: "overview", label: "Overview", icon: LayoutDashboard },
  { section: "vms", label: "Virtual machines", icon: Boxes },
  { section: "members", label: "Members", icon: Users },
  { section: "nodes", label: "Cluster nodes", icon: Server },
  { section: "accounts", label: "Cloud accounts", icon: Cloud },
  { section: "activity", label: "Activity", icon: Activity },
  { section: "jobs", label: "MPI jobs", icon: TerminalSquare },
  { section: "settings", label: "Settings", icon: Settings },
];

function StatusDot({ status }: { status: string }) { return <span className={`status-dot status-${status}`} aria-label={status} />; }
function StatusBadge({ status }: { status: string }) { return <span className={`status-badge status-${status}`}><StatusDot status={status} />{status.replaceAll("_", " ")}</span>; }
function PageTitle({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="page-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p className="muted">{description}</p></div>{action}</div>; }
function LoadingCard() { return <div className="loading-card" role="status">Loading workspace data…</div>; }
function ErrorCard({ message }: { message: string }) { return <div className="error-box" role="alert">{message}</div>; }

export function DashboardShell({ section }: { section: Section }) {
  const router = useRouter();
  const client = useQueryClient();
  const [toast, setToast] = useState("");
  const me = useQuery({ queryKey: ["me"], queryFn: () => api<{ user: CurrentUser }>("/api/me"), retry: false });
  const user = me.data?.user;
  useEffect(() => { if (me.error && (me.error as Error & { status?: number }).status === 401) router.replace("/login"); }, [me.error, router]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(""), 3500); return () => clearTimeout(timer); }, [toast]);

  async function logout() { await authClient.signOut(); client.clear(); router.replace("/login"); router.refresh(); }
  if (me.isPending) return <main className="state-screen" role="status"><Layers3 size={36} /><p>Opening your workspace…</p></main>;
  if (me.isError || !user) return <main className="state-screen"><XCircle size={36} /><h1>Account service unavailable</h1><p>Sign in again to reopen your workspace.</p><Button onClick={() => router.replace("/login")}>Return to sign in</Button></main>;
  return <div className="workspace"><aside className="workspace-sidebar"><Link href="/dashboard" className="brand"><Layers3 size={26} />{APP_NAME}</Link><span className="eyebrow">WORKSPACE</span><nav className="workspace-nav" aria-label="Workspace navigation">{nav.map(({ section: item, label, icon: Icon }) => <Link key={item} href={item === "overview" ? "/dashboard" : `/dashboard/${item}`} className={section === item ? "nav-item nav-item-active" : "nav-item"}><Icon size={17} />{label}</Link>)}</nav><div className="sidebar-bottom"><span className="provider-pill"><StatusDot status="online" />Mock cloud online</span><br />Beowulf Cluster Project<br /><span>University computing</span></div></aside><div className="workspace-body"><header className="workspace-header"><span><span className="header-context">Workspace</span><span className="slash">/</span>{nav.find(item => item.section === section)?.label}</span><div className="header-actions"><span className="user-chip"><span className="mini-avatar">{user.name.slice(0, 1).toUpperCase()}</span>{user.name}</span><Button variant="outline" size="sm" onClick={logout}><LogOut size={15} />Sign out</Button></div></header><main className="workspace-content">{toast && <div className="toast" role="status"><CheckCircle2 size={16} />{toast}</div>}<SectionView section={section} user={user} onToast={setToast} /></main></div></div>;
}

function SectionView({ section, user, onToast }: { section: Section; user: CurrentUser; onToast: (message: string) => void }) {
  if (section === "vms") return <VmsPage user={user} onToast={onToast} />;
  if (section === "members") return <MembersPage user={user} />;
  if (section === "nodes") return <NodesPage />;
  if (section === "accounts") return <AccountsPage user={user} onToast={onToast} />;
  if (section === "activity") return <ActivityPage />;
  if (section === "jobs") return <JobsPage onToast={onToast} />;
  if (section === "settings") return <SettingsPage user={user} />;
  return <OverviewPage user={user} onToast={onToast} />;
}

function OverviewPage({ user, onToast }: { user: CurrentUser; onToast: (message: string) => void }) {
  const query = useQuery({ queryKey: ["dashboard"], queryFn: () => api<{ status: { status: string; provider: string }; metrics: { nodesOnline: number; nodeCount: number; runningVms: number; totalUsers: number; cpuUsage: number; ramUsage: number }; nodes: ClusterNode[]; vms: VirtualMachine[]; activity: ActivityLog[] }>("/api/dashboard"), refetchInterval: 10000 });
  if (query.isPending) return <LoadingCard />; if (query.isError) return <ErrorCard message="The cluster overview could not be loaded." />;
  const { metrics, status, nodes, vms, activity } = query.data;
  return <><PageTitle eyebrow="COMMAND CENTER" title={`Good morning, ${user.name.split(" ")[0]}.`} description="A live view of your university computing workspace." /><section className="overview-hero"><div><span className="eyebrow">CLUSTER STATUS</span><div className="hero-status"><StatusDot status={status.status} /><strong>{status.status === "online" ? "Online" : "Offline"}</strong><span>•</span><span>{status.provider} provider</span></div><p>Mock mode is active and ready for development. The public API remains useful while a physical cluster is offline.</p></div><div className="hero-spark"><Zap size={18} /><span>Polling every 10s</span></div></section><div className="metric-grid"><Metric icon={<Server />} label="Nodes online" value={`${metrics.nodesOnline}/${metrics.nodeCount}`} detail="Cluster capacity" accent="teal" /><Metric icon={<Boxes />} label="Running VMs" value={String(metrics.runningVms)} detail="Across your workspace" accent="blue" /><Metric icon={<Users />} label="Members" value={String(metrics.totalUsers)} detail="Registered accounts" accent="violet" /><Metric icon={<Gauge />} label="Average CPU" value={`${metrics.cpuUsage}%`} detail={`${metrics.ramUsage}% memory used`} accent="amber" /></div><div className="content-grid"><section className="panel panel-wide"><div className="panel-heading"><div><span className="eyebrow">RECENT VIRTUAL MACHINES</span><h2>Your compute</h2></div><Link className="text-link" href="/dashboard/vms">View all <span>→</span></Link></div>{vms.length === 0 ? <Empty icon={<Boxes />} title="No virtual machines yet" description="Create your first VM to start using the mock cloud." action={<Link href="/dashboard/vms"><Button><Plus size={16} />Create VM</Button></Link>} /> : <VmTable vms={vms} compact onToast={onToast} />}</section><section className="panel"><div className="panel-heading"><div><span className="eyebrow">CLUSTER NODES</span><h2>Capacity</h2></div><Link className="text-link" href="/dashboard/nodes">Details <span>→</span></Link></div><div className="node-mini-list">{nodes.map(node => <div className="node-mini" key={node.id}><div><StatusDot status={node.status} /><strong>{node.hostname}</strong></div><span>{node.cpuUsage}% CPU</span></div>)}</div></section><section className="panel panel-wide"><div className="panel-heading"><div><span className="eyebrow">AUDIT TRAIL</span><h2>Recent activity</h2></div><Link className="text-link" href="/dashboard/activity">View all <span>→</span></Link></div><ActivityList items={activity} /></section></div></>;
}

function Metric({ icon, label, value, detail, accent }: { icon: React.ReactNode; label: string; value: string; detail: string; accent: string }) { return <div className={`metric-card metric-${accent}`}><div className="metric-icon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }
function Empty({ icon, title, description, action }: { icon: React.ReactNode; title: string; description: string; action?: React.ReactNode }) { return <div className="empty-state"><div className="empty-icon">{icon}</div><h3>{title}</h3><p>{description}</p>{action}</div>; }

function VmsPage({ user, onToast }: { user: CurrentUser; onToast: (message: string) => void }) {
  const client = useQueryClient(); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState({ name: "", image: "Ubuntu 24.04 LTS", cpu: "2", memoryMb: "2048", diskGb: "10" });
  const query = useQuery({ queryKey: ["vms"], queryFn: () => api<{ vms: VirtualMachine[] }>("/api/vms"), refetchInterval: 7000 });
  const create = useMutation({ mutationFn: () => api<VirtualMachine>("/api/vms", { method: "POST", body: JSON.stringify({ ...form, cpu: Number(form.cpu), memoryMb: Number(form.memoryMb), diskGb: Number(form.diskGb) }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["vms"] }); setShowForm(false); setForm({ name: "", image: "Ubuntu 24.04 LTS", cpu: "2", memoryMb: "2048", diskGb: "10" }); onToast("Virtual machine created. It will be running shortly."); } });
  if (query.isPending) return <LoadingCard />; if (query.isError) return <ErrorCard message="Virtual machines could not be loaded." />;
  return <><PageTitle eyebrow="COMPUTE" title="Virtual machines" description={user.role === "admin" ? "Manage every VM in the workspace." : "Create and manage your own research environments."} action={<Button onClick={() => setShowForm(!showForm)}><Plus size={16} />New VM</Button>} />{showForm && <form className="create-panel" onSubmit={event => { event.preventDefault(); create.mutate(); }}><div className="form-heading"><div><span className="eyebrow">NEW INSTANCE</span><h2>Configure a virtual machine</h2></div><button type="button" className="icon-button" onClick={() => setShowForm(false)} aria-label="Close"><XCircle size={19} /></button></div><div className="form-grid"><label>VM name<Input required value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder="e.g. mpi-worker" /></label><label>Image<select value={form.image} onChange={event => setForm({ ...form, image: event.target.value })}><option>Ubuntu 24.04 LTS</option><option>Rocky Linux 9</option><option>Debian 12</option></select></label><label>CPU cores<select value={form.cpu} onChange={event => setForm({ ...form, cpu: event.target.value })}><option value="1">1 core</option><option value="2">2 cores</option><option value="4">4 cores</option></select></label><label>Memory<select value={form.memoryMb} onChange={event => setForm({ ...form, memoryMb: event.target.value })}><option value="512">512 MB</option><option value="1024">1 GB</option><option value="2048">2 GB</option><option value="4096">4 GB</option></select></label><label>Disk<select value={form.diskGb} onChange={event => setForm({ ...form, diskGb: event.target.value })}><option value="5">5 GB</option><option value="10">10 GB</option><option value="20">20 GB</option></select></label></div>{create.error && <ErrorCard message={(create.error as Error).message} />}<div className="form-actions"><Button type="button" variant="outline" onClick={() => setShowForm(false)}>Cancel</Button><Button disabled={create.isPending} type="submit">{create.isPending ? "Creating…" : "Create VM"}</Button></div></form>}<section className="panel"><div className="panel-heading"><div><span className="eyebrow">INVENTORY</span><h2>{query.data.vms.length} virtual machines</h2></div><span className="subtle-label"><StatusDot status="online" />Mock provider</span></div>{query.data.vms.length ? <VmTable vms={query.data.vms} onToast={onToast} /> : <Empty icon={<Boxes />} title="No virtual machines" description="Your first research environment is one click away." action={<Button onClick={() => setShowForm(true)}><Plus size={16} />Create VM</Button>} />}</section></>;
}

function VmTable({ vms, compact = false, onToast }: { vms: VirtualMachine[]; compact?: boolean; onToast: (message: string) => void }) { const client = useQueryClient(); const action = useMutation({ mutationFn: async ({ id, verb }: { id: string; verb: string }) => { if (verb === "delete") return api<void>(`/api/vms/${id}`, { method: "DELETE" }); return api<VirtualMachine>(`/api/vms/${id}/${verb}`, { method: "POST" }); }, onSuccess: (_data, variables) => { client.invalidateQueries({ queryKey: ["vms"] }); client.invalidateQueries({ queryKey: ["dashboard"] }); const labels: Record<string, string> = { start: "started", stop: "stopped", reboot: "rebooted" }; onToast(variables.verb === "delete" ? "Virtual machine deleted." : `Virtual machine ${labels[variables.verb] ?? variables.verb}.`); } }); return <div className="table-wrap"><table><thead><tr><th>Name</th><th>Status</th>{!compact && <><th>Owner</th><th>Resources</th><th>Host</th></>}<th aria-label="Actions" /></tr></thead><tbody>{vms.map(vm => <tr key={vm.id}><td><div className="table-primary"><span className="vm-mark"><Boxes size={15} /></span><div><strong>{vm.name}</strong><small>{vm.image}</small></div></div></td><td><StatusBadge status={vm.status} /></td>{!compact && <><td>{vm.ownerName}</td><td>{vm.cpu} vCPU · {vm.memoryMb >= 1024 ? `${vm.memoryMb / 1024} GB` : `${vm.memoryMb} MB`} · {vm.diskGb} GB</td><td>{vm.host ?? "—"}</td></>}<td><div className="row-actions">{vm.status === "running" ? <button onClick={() => action.mutate({ id: vm.id, verb: "stop" })} aria-label={`Stop ${vm.name}`}><Square size={15} /></button> : vm.status === "stopped" ? <button onClick={() => action.mutate({ id: vm.id, verb: "start" })} aria-label={`Start ${vm.name}`}><Play size={15} /></button> : null}<button onClick={() => action.mutate({ id: vm.id, verb: "reboot" })} aria-label={`Reboot ${vm.name}`}><Zap size={15} /></button><button className="danger-action" onClick={() => { if (window.confirm(`Delete ${vm.name}?`)) action.mutate({ id: vm.id, verb: "delete" }); }} aria-label={`Delete ${vm.name}`}><Trash2 size={15} /></button></div></td></tr>)}</tbody></table></div>; }

function MembersPage({ user }: { user: CurrentUser }) { const query = useQuery({ queryKey: ["users"], queryFn: () => api<{ users: Array<CurrentUser & { cloudAccountStatus: string }> }>("/api/users") }); if (query.isPending) return <LoadingCard />; if (query.isError) return <ErrorCard message="Member directory could not be loaded." />; return <><PageTitle eyebrow="COMMUNITY" title="Members" description="People with access to the university computing workspace." /><section className="panel"><div className="panel-heading"><div><span className="eyebrow">DIRECTORY</span><h2>{query.data.users.length} registered members</h2></div><span className="subtle-label"><Users size={15} />Shared workspace</span></div><div className="member-grid">{query.data.users.map(member => <article className="member-card" key={member.id}><div className="avatar">{member.name.slice(0, 1).toUpperCase()}</div><div><h3>{member.name}{member.id === user.id && <span className="you-label">You</span>}</h3><p>{member.email}</p><div className="member-meta"><StatusDot status="online" />Active <span>·</span><span className="role-badge">{member.role}</span></div><div className="member-account"><StatusDot status={member.cloudAccountStatus === "active" ? "online" : "pending"} />Cloud account: {member.cloudAccountStatus.replaceAll("_", " ")} · Joined {new Date(member.createdAt).toLocaleDateString()}</div></div></article>)}</div></section></>; }

function NodesPage() { const query = useQuery({ queryKey: ["nodes"], queryFn: () => api<{ nodes: ClusterNode[] }>("/api/nodes"), refetchInterval: 10000 }); if (query.isPending) return <LoadingCard />; if (query.isError) return <ErrorCard message="Cluster nodes could not be loaded." />; return <><PageTitle eyebrow="INFRASTRUCTURE" title="Cluster nodes" description="Health and capacity across the Beowulf cluster." /><div className="node-grid">{query.data.nodes.map(node => <article className="node-card" key={node.id}><div className="node-card-head"><div><StatusBadge status={node.status} /><h2>{node.hostname}</h2><p>{node.ipAddress}</p></div><Server size={24} /></div><div className="node-metrics"><Meter icon={<Cpu size={15} />} label="CPU" value={node.cpuUsage} /><Meter icon={<MemoryStick size={15} />} label="Memory" value={node.ramUsage} /><Meter icon={<Gauge size={15} />} label="Disk" value={node.diskUsage} /></div><dl className="node-specs"><div><dt>Compute</dt><dd>{node.cpuCores} cores</dd></div><div><dt>RAM</dt><dd>{node.memoryMb / 1024} GB</dd></div><div><dt>Uptime</dt><dd>{node.uptime}</dd></div></dl></article>)}</div></>; }
function Meter({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <div className="meter"><div><span>{icon}{label}</span><strong>{value}%</strong></div><div className="meter-track"><span style={{ width: `${value}%` }} /></div></div>; }

function AccountsPage({ user, onToast }: { user: CurrentUser; onToast: (message: string) => void }) { const client = useQueryClient(); const query = useQuery({ queryKey: ["accounts"], queryFn: () => api<{ accounts: CloudAccount[] }>("/api/cloud-accounts") }); const provision = useMutation({ mutationFn: (userId?: string) => api<CloudAccount>("/api/cloud-accounts/provision", { method: "POST", body: JSON.stringify(userId ? { userId } : {}) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["accounts"] }); onToast("Cloud account provisioned in mock mode."); } }); if (query.isPending) return <LoadingCard />; if (query.isError) return <ErrorCard message="Cloud accounts could not be loaded." />; return <><PageTitle eyebrow="IDENTITY BRIDGE" title="Cloud accounts" description="Application identities mapped to provider accounts." /><section className="panel"><div className="panel-heading"><div><span className="eyebrow">PROVISIONING</span><h2>Provider access</h2></div><Cloud size={22} /></div><div className="account-list">{query.data.accounts.map(account => <div className="account-row" key={account.id}><div className="avatar avatar-small">{account.username?.slice(4, 5).toUpperCase() ?? "?"}</div><div className="account-info"><strong>{account.userId === user.id ? "Your cloud account" : `Member ${account.userId.slice(0, 8)}`}</strong><small>{account.username ?? "No provider username yet"}</small></div><StatusBadge status={account.status} /><div className="row-actions">{account.status === "not_provisioned" && <Button size="sm" onClick={() => provision.mutate(account.userId)} disabled={provision.isPending}>Provision</Button>}</div></div>)}</div></section></>; }

function ActivityPage() { const query = useQuery({ queryKey: ["activity"], queryFn: () => api<{ activity: ActivityLog[] }>("/api/activity") }); if (query.isPending) return <LoadingCard />; if (query.isError) return <ErrorCard message="Activity could not be loaded." />; return <><PageTitle eyebrow="AUDIT TRAIL" title="Activity" description="A record of important workspace operations." /><section className="panel"><ActivityList items={query.data.activity} expanded /></section></>; }
function ActivityList({ items, expanded = false }: { items: ActivityLog[]; expanded?: boolean }) { return items.length ? <div className="activity-list">{items.slice(0, expanded ? 100 : 6).map(item => <div className="activity-row" key={item.id}><div className="activity-icon"><Activity size={15} /></div><div><strong>{item.action}</strong><p>{item.userName} · {item.resourceType.replaceAll("_", " ")}</p></div><time>{new Date(item.createdAt).toLocaleString(undefined, { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" })}</time></div>)}</div> : <Empty icon={<Activity />} title="No activity yet" description="Your workspace operations will appear here." />; }

function JobsPage({ onToast }: { onToast: (message: string) => void }) { const client = useQueryClient(); const [form, setForm] = useState({ name: "", program: "matrix-multiply", processCount: "4" }); const query = useQuery({ queryKey: ["jobs"], queryFn: () => api<{ jobs: MpiJob[] }>("/api/jobs"), refetchInterval: 2000 }); const create = useMutation({ mutationFn: () => api<MpiJob>("/api/jobs", { method: "POST", body: JSON.stringify({ ...form, processCount: Number(form.processCount) }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["jobs"] }); setForm({ name: "", program: "matrix-multiply", processCount: "4" }); onToast("MPI job queued in mock mode."); } }); if (query.isPending) return <LoadingCard />; if (query.isError) return <ErrorCard message="MPI jobs could not be loaded." />; return <><PageTitle eyebrow="HIGH PERFORMANCE COMPUTING" title="MPI jobs" description="Run predefined MPI workloads through the controlled cluster interface." /><section className="job-layout"><form className="panel job-form" onSubmit={event => { event.preventDefault(); create.mutate(); }}><span className="eyebrow">SUBMIT WORKLOAD</span><h2>New MPI job</h2><p className="muted">Only approved programs can run through the cluster agent.</p><label>Job name<Input required value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder="e.g. benchmark run" /></label><label>Program<select value={form.program} onChange={event => setForm({ ...form, program: event.target.value })}><option value="matrix-multiply">Matrix multiply</option><option value="calculate-pi">Calculate pi</option><option value="vector-addition">Vector addition</option></select></label><label>Processes<select value={form.processCount} onChange={event => setForm({ ...form, processCount: event.target.value })}><option value="2">2 processes</option><option value="4">4 processes</option><option value="8">8 processes</option><option value="16">16 processes</option></select></label>{create.error && <ErrorCard message={(create.error as Error).message} />}<Button type="submit" disabled={create.isPending}><Play size={15} />{create.isPending ? "Submitting…" : "Queue job"}</Button></form><section className="panel"><div className="panel-heading"><div><span className="eyebrow">QUEUE</span><h2>Recent jobs</h2></div><TerminalSquare size={22} /></div>{query.data.jobs.length ? <div className="job-list">{query.data.jobs.map(job => <div className="job-row" key={job.id}><div className="job-mark"><TerminalSquare size={15} /></div><div><strong>{job.name}</strong><small>{job.program} · {job.processCount} processes · {job.userName}</small></div><StatusBadge status={job.status} /></div>)}</div> : <Empty icon={<TerminalSquare />} title="No MPI jobs" description="Queue a predefined workload when you are ready." />}</section></section></>; }

function SettingsPage({ user }: { user: CurrentUser }) { return <><PageTitle eyebrow="WORKSPACE" title="Settings" description="Your account and environment information." /><section className="settings-grid"><div className="panel"><span className="eyebrow">PROFILE</span><h2>{user.name}</h2><p className="muted">{user.email}</p><dl className="settings-list"><div><dt>Role</dt><dd><span className="role-badge">{user.role}</span></dd></div><div><dt>Member since</dt><dd>{new Date(user.createdAt).toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" })}</dd></div></dl></div><div className="panel"><span className="eyebrow">ENVIRONMENT</span><h2>Mock cloud</h2><p className="muted">Safe local development provider</p><div className="environment-status"><StatusDot status="online" /><strong>Connected</strong><span>SQLite-backed local workspace</span></div><div className="security-note"><ShieldCheck size={20} /><span>Infrastructure credentials are kept out of the browser. OpenNebula integration is isolated to the future cluster agent.</span></div></div></section></>; }
